// Shared helpers for showing, editing and downloading generated documents.

const DOC_CSS = 'body{font-family:Georgia,serif;max-width:800px;margin:40px auto;padding:0 40px;color:#1a1a1a;line-height:1.7;}h1{font-size:24px;}h1{border-bottom:3px solid #1F57F0;padding-bottom:10px;}h2{font-size:16px;color:#1F57F0;border-left:4px solid #1F57F0;padding-left:10px;margin-top:28px;}.keypoints{background:#EAF0FE;border-left:4px solid #1F57F0;padding:12px 16px 2px;margin-bottom:20px;}p,li{font-size:14px;margin-bottom:10px;}ul{padding-left:22px;}table{border-collapse:collapse;width:100%;margin:12px 0;font-size:13px;}th,td{border:1px solid #CFC8BF;padding:8px 10px;text-align:left;vertical-align:top;}th{background:#F2EFEA;}@media print{body{margin:0;padding:20px;}}';

// Generated or edited HTML is cleaned before it is shown, saved or downloaded.
export function sanitizeHtml(html) {
  return String(html || '')
    .replace(/<\s*(script|style|iframe|object|embed|link|meta)\b[^>]*>[\s\S]*?<\s*\/\s*\1\s*>/gi, '')
    .replace(/<\s*(script|style|iframe|object|embed|link|meta)\b[^>]*>/gi, '')
    .replace(/\son\w+\s*=\s*("[^"]*"|'[^']*'|[^\s>]+)/gi, '')
    .replace(/(href|src)\s*=\s*(["'])\s*javascript:[^"']*\2/gi, '$1=$2#$2');
}

export function buildDocHtml(html, title) {
  const safeTitle = String(title || 'Document').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${safeTitle}</title><style>${DOC_CSS}</style></head><body>${sanitizeHtml(html)}<p style="margin-top:40px;font-size:12px;color:#5F5852;border-top:1px solid #E3DED7;padding-top:16px;">Generated by PM Buddy &middot; ${date}</p></body></html>`;
}

function fileName(title, ext) {
  return `${String(title || 'Document').replace(/[^\w\- ]+/g, '').trim().replace(/\s+/g, '_')}.${ext}`;
}

function saveBlob(blob, name) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = name;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

// Old way: open a print window. Only used if the real PDF could not be built.
function printFallback(html, title) {
  const w = window.open('', '_blank');
  if (!w) return false;
  w.document.write(buildDocHtml(html, title));
  w.document.close();
  w.focus();
  setTimeout(() => w.print(), 500);
  return true;
}

function legacyWord(html, title) {
  saveBlob(new Blob([buildDocHtml(html, title)], { type: 'application/msword' }), fileName(title, 'doc'));
}

// Both return true when a file was produced.
export async function downloadPDF(html, title) {
  try {
    const [{ htmlToBlocks }, { buildPdfBlob }] = await Promise.all([import('./docModel'), import('./docFormats')]);
    saveBlob(await buildPdfBlob(htmlToBlocks(sanitizeHtml(html)), title), fileName(title, 'pdf'));
    return true;
  } catch (err) {
    return printFallback(html, title);
  }
}

export async function downloadWord(html, title) {
  try {
    const [{ htmlToBlocks }, { buildDocxBlob }] = await Promise.all([import('./docModel'), import('./docFormats')]);
    saveBlob(await buildDocxBlob(htmlToBlocks(sanitizeHtml(html)), title), fileName(title, 'docx'));
  } catch (err) {
    legacyWord(html, title);
  }
  return true;
}
