// Shared helpers for showing, editing and downloading generated documents.

const DOC_CSS = 'body{font-family:Georgia,serif;max-width:800px;margin:40px auto;padding:0 40px;color:#1a1a1a;line-height:1.7;}h1{font-size:24px;}h2{font-size:16px;color:#1F57F0;text-transform:uppercase;border-bottom:1px solid #E3DED7;padding-bottom:6px;margin-top:28px;}p,li{font-size:14px;margin-bottom:10px;}ul{padding-left:22px;}table{border-collapse:collapse;width:100%;margin:12px 0;font-size:13px;}th,td{border:1px solid #CFC8BF;padding:8px 10px;text-align:left;vertical-align:top;}th{background:#F2EFEA;}@media print{body{margin:0;padding:20px;}}';

// Generated or edited HTML is cleaned before it is shown, saved or downloaded.
export function sanitizeHtml(html) {
  return String(html || '')
    .replace(/<\s*(script|style|iframe|object|embed|link|meta)\b[^>]*>[\s\S]*?<\s*\/\s*\1\s*>/gi, '')
    .replace(/<\s*(script|style|iframe|object|embed|link|meta)\b[^>]*>/gi, '')
    .replace(/\son\w+\s*=\s*("[^"]*"|'[^']*'|[^\s>]+)/gi, '')
    .replace(/(href|src)\s*=\s*(["'])\s*javascript:[^"']*\2/gi, '$1=$2#$2');
}

export function buildDocHtml(html, title) {
  const safeTitle = String(title || 'Document').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${safeTitle}</title><style>${DOC_CSS}</style></head><body>${sanitizeHtml(html)}<p style="margin-top:40px;font-size:12px;color:#5F5852;border-top:1px solid #E3DED7;padding-top:16px;">Generated by PM Buddy &middot; ${date}</p></body></html>`;
}

export function downloadPDF(html, title) {
  const w = window.open('', '_blank');
  if (!w) return false;
  w.document.write(buildDocHtml(html, title));
  w.document.close();
  w.focus();
  setTimeout(() => w.print(), 500);
  return true;
}

export function downloadWord(html, title) {
  const blob = new Blob([buildDocHtml(html, title)], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${String(title || 'Document').replace(/[^\w\- ]+/g, '').trim().replace(/\s+/g, '_')}.doc`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
