// Builds real Word (.docx) and PDF files from the shared blocks in docModel.js.
// The libraries are large, so they are only loaded when someone downloads a file.

const INK = '1E1919';
const MUTED = '5F5852';
const ACCENT = '1F57F0';
const BORDER = 'CFC8BF';
const HEADER_FILL = 'F2EFEA';
const CALLOUT_FILL = 'EAF0FE';

function footerText() {
  const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
  return `Generated by PM Buddy · ${date}`;
}

// ---------- Word ----------
export async function buildDocxBlob(blocks, title) {
  const {
    Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell,
    WidthType, BorderStyle, ShadingType, AlignmentType, Footer, LevelFormat,
  } = await import('docx');

  const toRuns = (runs, extra = {}) => runs.flatMap((r) => {
    const parts = r.text.split('\n');
    return parts.map((part, i) => new TextRun({ text: part, bold: r.bold || extra.bold, italics: r.italic, color: extra.color, size: extra.size, break: i > 0 ? 1 : undefined }));
  });

  const border = { style: BorderStyle.SINGLE, size: 4, color: BORDER };
  const cellBorders = { top: border, bottom: border, left: border, right: border };

  const render = (block) => {
    const children = [];
    if (block.type === 'heading') {
      const sizes = { 1: 40, 2: 28, 3: 24 };
      const levels = { 1: HeadingLevel.HEADING_1, 2: HeadingLevel.HEADING_2, 3: HeadingLevel.HEADING_3 };
      children.push(new Paragraph({
        heading: levels[block.level],
        spacing: { before: block.level === 1 ? 0 : 320, after: 140 },
        border: block.level === 2 ? { bottom: { style: BorderStyle.SINGLE, size: 6, color: 'E3DED7', space: 4 } } : undefined,
        children: toRuns(block.runs, { bold: true, color: block.level === 2 ? ACCENT : INK, size: sizes[block.level] }),
      }));
    } else if (block.type === 'paragraph') {
      children.push(new Paragraph({ spacing: { after: 140, line: 300 }, children: toRuns(block.runs, { size: 22 }) }));
    } else if (block.type === 'list') {
      block.items.forEach((runs) => {
        children.push(new Paragraph({
          numbering: { reference: block.ordered ? 'numbers' : 'bullets', level: 0 },
          spacing: { after: 80, line: 300 },
          children: toRuns(runs, { size: 22 }),
        }));
      });
    } else if (block.type === 'callout') {
      const none = { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' };
      children.push(new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [new TableRow({ children: [new TableCell({
          borders: { top: none, bottom: none, right: none, left: { style: BorderStyle.SINGLE, size: 24, color: ACCENT } },
          shading: { type: ShadingType.CLEAR, fill: CALLOUT_FILL, color: 'auto' },
          margins: { top: 120, bottom: 120, left: 200, right: 160 },
          children: block.blocks.flatMap(render).filter(c => c instanceof Paragraph),
        })] })],
      }));
      children.push(new Paragraph({ spacing: { after: 160 }, children: [] }));
    } else if (block.type === 'table') {
      const cols = Math.max(...block.rows.map(r => r.length));
      children.push(new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: block.rows.map((row) => new TableRow({
          tableHeader: row.every(c => c.header),
          children: Array.from({ length: cols }, (_, i) => {
            const cell = row[i] || { runs: [], header: false };
            return new TableCell({
              borders: cellBorders,
              width: { size: Math.floor(100 / cols), type: WidthType.PERCENTAGE },
              shading: cell.header ? { type: ShadingType.CLEAR, fill: HEADER_FILL, color: 'auto' } : undefined,
              margins: { top: 80, bottom: 80, left: 100, right: 100 },
              children: [new Paragraph({ children: toRuns(cell.runs, { size: 20, bold: cell.header }) })],
            });
          }),
        })),
      }));
      children.push(new Paragraph({ spacing: { after: 160 }, children: [] }));
    }
    return children;
  };

  const children = blocks.flatMap(render);

  const doc = new Document({
    creator: 'PM Buddy',
    title: String(title || 'Document'),
    styles: { default: { document: { run: { font: 'Calibri', size: 22, color: INK } } } },
    numbering: {
      config: [
        { reference: 'bullets', levels: [{ level: 0, format: LevelFormat.BULLET, text: '•', alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 540, hanging: 270 } } } }] },
        { reference: 'numbers', levels: [{ level: 0, format: LevelFormat.DECIMAL, text: '%1.', alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 540, hanging: 270 } } } }] },
      ],
    },
    sections: [{
      properties: { page: { margin: { top: 1134, bottom: 1134, left: 1134, right: 1134 } } },
      footers: { default: new Footer({ children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: footerText(), size: 16, color: MUTED })] })] }) },
      children,
    }],
  });
  return Packer.toBlob(doc);
}

// ---------- PDF ----------
export async function buildPdfBlob(blocks, title) {
  const pdfMakeModule = await import('pdfmake/build/pdfmake');
  const fontsModule = await import('pdfmake/build/vfs_fonts');
  const pdfMake = pdfMakeModule.default || pdfMakeModule;
  const fonts = fontsModule.default || fontsModule;
  pdfMake.vfs = (fonts.pdfMake && fonts.pdfMake.vfs) || fonts.vfs || fonts;

  const toText = (runs) => runs.map(r => ({ text: r.text, bold: r.bold, italics: r.italic }));

  const renderBlock = (block) => {
    if (block.type === 'callout') {
      return {
        margin: [0, 2, 0, 12],
        table: { widths: ['*'], body: [[{ stack: block.blocks.map(renderBlock), fillColor: `#${CALLOUT_FILL}`, margin: [8, 6, 8, 2] }]] },
        layout: { hLineWidth: () => 0, vLineWidth: (i) => (i === 0 ? 3 : 0), vLineColor: () => `#${ACCENT}` },
      };
    }
    if (block.type === 'heading') {
      const style = { 1: { fontSize: 20, bold: true, color: `#${INK}`, margin: [0, 0, 0, 10] }, 2: { fontSize: 13.5, bold: true, color: `#${ACCENT}`, margin: [0, 16, 0, 6] }, 3: { fontSize: 11.5, bold: true, color: `#${INK}`, margin: [0, 10, 0, 4] } }[block.level];
      return { text: toText(block.runs), ...style };
    }
    if (block.type === 'paragraph') return { text: toText(block.runs), margin: [0, 0, 0, 7] };
    if (block.type === 'list') {
      const items = block.items.map(runs => ({ text: toText(runs) }));
      return block.ordered ? { ol: items, margin: [0, 0, 0, 7] } : { ul: items, margin: [0, 0, 0, 7] };
    }
    const cols = Math.max(...block.rows.map(r => r.length));
    return {
      margin: [0, 4, 0, 12],
      table: {
        headerRows: block.rows[0] && block.rows[0].every(c => c.header) ? 1 : 0,
        widths: Array.from({ length: cols }, () => '*'),
        body: block.rows.map(row => Array.from({ length: cols }, (_, i) => {
          const cell = row[i] || { runs: [], header: false };
          return { text: toText(cell.runs), bold: cell.header, fillColor: cell.header ? `#${HEADER_FILL}` : undefined, fontSize: 9.5, margin: [2, 3, 2, 3] };
        })),
      },
      layout: { hLineColor: () => `#${BORDER}`, vLineColor: () => `#${BORDER}`, hLineWidth: () => 0.6, vLineWidth: () => 0.6 },
    };
  };
  const content = blocks.map(renderBlock);

  const definition = {
    info: { title: String(title || 'Document'), author: 'PM Buddy' },
    pageSize: 'A4',
    pageMargins: [56, 56, 56, 64],
    defaultStyle: { font: 'Roboto', fontSize: 10.5, lineHeight: 1.35, color: `#${INK}` },
    content,
    footer: (page, pages) => ({ text: `${footerText()}    Page ${page} of ${pages}`, alignment: 'center', fontSize: 8, color: `#${MUTED}`, margin: [0, 22, 0, 0] }),
  };

  return new Promise((resolve, reject) => {
    try { pdfMake.createPdf(definition).getBlob(resolve); } catch (err) { reject(err); }
  });
}
