// Plain-English explanations for the (i) pointers. Keep each one short: what it is, and why it matters.
export const GLOSSARY = {
  progress: { title: 'Progress overview', text: 'A quick picture of how far along the project is. The ring counts finished tasks and milestones out of everything in the project.' },
  tasks: { title: 'Tasks', text: 'Small pieces of work that one person can finish, such as "Book the venue". Tick them off as you go.' },
  milestones: { title: 'Milestones', text: 'The big checkpoints on the way, such as "First draft ready" or "Launch day". They help you see progress without counting every small task.' },
  overdue: { title: 'Overdue', text: 'Tasks whose due date has passed and which are not marked done yet.' },
  dueThisWeek: { title: 'Due this week', text: 'Tasks that are due in the next 7 days and are not done yet.' },
  openRisks: { title: 'Open risks', text: 'Things that could go wrong and have not been dealt with yet. Spotting them early gives you time to act.' },
  team: { title: 'Team', text: 'The people working on this project. Add them in the People tab, and they get a notification when something changes.' },
  success: { title: 'What success looks like', text: 'One or two sentences about what will be different when the project is finished. It keeps everyone aiming at the same thing.' },
  currentStatus: { title: 'Current status', text: 'A short note on where things stand today: what stage you are at, what is finished, and what is left to do.' },
  taskBoard: { title: 'Task board', text: 'Tasks sit in three columns: To Do, In Progress and Done. Move a task along as the work moves. Milestones appear here as cards too.' },
  blocker: { title: 'Blocker', text: 'A task that is stuck and holding other work up. Flagging it makes it stand out so it gets attention first.' },
  taskNotes: { title: 'Notes on a task', text: 'Write an update or a decision on the task, such as "waiting for the venue to reply". The team can read it.' },
  boardNotes: { title: 'Project notes', text: 'A shared place for things that belong to the whole project, such as meeting notes and decisions. Everyone on the project can see them.' },
  risks: { title: 'What could go wrong', text: 'Risks are possible problems. Write each one and say how serious it would be. High means it would badly hurt the project. Low means a small nuisance.' },
  compliance: { title: 'Rules and compliance', text: 'Laws, funder conditions or policies that this project has to follow, such as protecting people\'s personal data. Listing them helps you not forget one.' },
  yourTeam: { title: 'Your team', text: 'The people doing the work. Each person\'s role says what they are responsible for.' },
  stakeholders: { title: 'People with an interest', text: 'People who care about the project but may not do the work, such as a funder, a manager or the community. Keep them informed.' },
  updates: { title: 'How we share updates', text: 'How, and how often, the team stays in touch. For example a weekly WhatsApp message or a Friday call.' },
  reminders: { title: 'Reminders', text: 'Emails that remind you and the team before something is due, so nothing slips.' },
  healthCheck: { title: 'Health check', text: 'PM Buddy reads your project and scores how complete and well planned it is, with the biggest gaps and how to fix them.' },
  progressMap: { title: 'Progress map', text: 'A short plain-English story of where the project started, what has been achieved, and what to focus on next.' },
  pmPlan: { title: 'PM plan', text: 'A full project plan written from your project details: summary, team, timeline, risks and more. You can edit it and download it as Word or PDF.' },
  history: { title: 'History', text: 'A log of what changed in the project and when, such as tasks moved or notes added.' },
};
